[package]
name = "self-ref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ip-init = { path = '../ip-init' }
pin-project = '1'